# Generated by Django 4.2.4 on 2023-08-22 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entregas',
        ),
    ]
